### PR TITLE
don't show banner when tentative winner radio button is selected

### PR DESCRIPTION
**Pull request by bthaile**
don't show red banner when tentative winning outcome is selected.

image

image

### CODE REVIEW

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Can you fix the svg alert icon there? Has a weird background

**Comment by bthaile** [comment]
it's same as market create Error. 
image

**Comment by phoebemirman** [comment]
the background looks off
Screen Shot 2019-10-02 at 11 21 59 AM

**Comment by bthaile** [comment]
I see the icon is off.

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🏅

 This link will always point to this PR's latest changes: https://peek.run/g7oh4r6

**Review by phoebemirman — APPROVED** [review]
lg except icon thing

**Pull request merged**
