### PR TITLE
update assets on block updates instead of spamming it on some blocks

### PR DESCRIPTION
**Pull request by nuevoalex**
Did essentially what we discussed. Works well.

[Clubhouse Story](https://app.clubhouse.io/augur/story/11696)

## Submitter checklist
- [ ] Test covering functionality added/fixed in
- Check the linked story includes the following:
  - [ ] Steps to reproduce
  - [ ] Screenshot (If applicable)

## Reviewer Checklist
- [ ] Test/lint pass

### CODE REVIEW

**Comment by tinybike** [comment]
This is a bad fix and should be reverted IMO.

**Comment by tinybike** [comment]
It would be really good to fix this *without* calling updateAssets on every single block.  There's a lot of overhead associated with that that we've made a point of avoiding by not doing this.

**Comment by tinybike** [comment]
(I'm assuming the overall impact of updateAssets on every block is greater than calling it multiple times if you happen to get a block with multiple updateAssets-calling log processors -- is that incorrect?)

**Comment by nuevoalex** [comment]
On mainnet blocks come in every 15 seconds. Even on private chain they come in every 2 seconds or so. Why do you think this is incurring large overhead?

**Pull request merged**
