### PR TITLE
#12 create market assertions

### PR DESCRIPTION
**Pull request by stephensprinkle**
Changes present here will also require the changes present in AURC's PR #33.

### CODE REVIEW

**Comment by stephensprinkle** [comment]
btw, those failures are to-be-expected until AURC is updated.

**Comment by thinkloop** [comment]
Looks good, should I merge then even with those errors or are you saying to wait?

**Comment by stephensprinkle** [comment]
Awesome, go for it.  With the changes on the AURC side pushed to NPM, these should now be resolved.

**Comment by tinybike** [comment]
@stephensprinkle I'm still getting the same errors as before, even when I set the AURC dependency to Github:
```
  1) modules/create-market/selectors/create-market-form.js step 1 should deliver the correct values to components:
     TypeError: componentAssertions.step1 is not a function
      at Context.<anonymous> (create-market-form-test.js:92:24)

  2) modules/create-market/selectors/create-market-form.js step 2 should deliver the correct values to components:
     TypeError: componentAssertions.step2 is not a function
      at create-market-form-test.js:159:25
      at Array.map (native)
      at Context.<anonymous> (create-market-form-test.js:141:10)

  3) modules/create-market/selectors/create-market-form.js step 3 should deliver the correct values to components:
     TypeError: componentAssertions.step3 is not a function
      at Context.<anonymous> (create-market-form-test.js:199:24)

  4) modules/create-market/selectors/create-market-form.js step 4 should deliver the correct values to components:
     TypeError: componentAssertions.step4 is not a function
      at Context.<anonymous> (create-market-form-test.js:244:24)

  5) modules/create-market/selectors/create-market-form.js step 5 should deliver the correct values to components:
     TypeError: componentAssertions.step5 is not a function
      at Context.<anonymous> (create-market-form-test.js:276:24)
```

**Comment by stephensprinkle** [comment]
Ok, I'll take a look again on my end.

**Comment by stephensprinkle** [comment]
@tinybike -- PR [#40](https://github.com/AugurProject/augur-ui-react-components/pull/40) will resolve the issue here.  I made a change to `assertions/index.js` and failed to reflect the implications of those changes over into `createMarketForm.js`

**Pull request merged**
