### PR TITLE
Add support for trezor authentication

### LINKED ISSUE #1472: Integrate Trezor as authentication method
Using the Trezor API, integrate Trezor as an authentication/account method for the Augur UI. 

Please join the #dev or #bounties channel of our [Discord](http://augur.net/invite) with any questions. 

Bounty posted with [Gitcoin](https://gitcoin.co).

### PR DESCRIPTION
**Pull request by meowingtwurtle**
NOTE: This is thoroughly untested as I still don't have a Trezor, though I think it *should* work (no promises).

This code is guarantted to request only the following from Trezor: Account info, address of account, ethereum transaction via ethrpc.

Closes #1472.

### CODE REVIEW

**Comment by tomkysar** [comment]
I just tested this @meowingtwurtle, the connection to Trezor itself works, however, the pop-up modal is only allowing you to export a Bitcoin wallet. If you select one of the Bitcoin wallets, it returns an error and fails. It will need to export the Trezors Ethereum accounts.

**Comment by meowingtwurtle** [comment]
Okay. That's kind of what I expected, but I couldn't test it. Apparently the API doesn't support automatic Ethereum account discovery (neither does the lower level API). However (after browsing MyEtherWallet's code for Trezor), it does appear that it can get an account by ID. So, it could either: always get the first Ethereum account or use a spinner to let them select an account number.

**Comment by meowingtwurtle** [comment]
For testing, I'll just use the first one for now.

**Comment by meowingtwurtle** [comment]
Actually, I'm going to try something else first.

**Comment by meowingtwurtle** [comment]
That code is very untested and a bit hacky, but it's the only way I could think f to do this.

**Comment by sharkcrayon** [comment]
@tinybike @tomkysar What needs to happen here?

**Comment by sharkcrayon** [comment]
K, sounds good :)

**Comment by meowingtwurtle** [comment]
Okay, I realize my bounty timer is almost up (2 days as of now). I just pushed some changes that work to fix things. However, as I have said in the issue itself, this: https://github.com/trezor/connect/issues/121 is a blocker. It's probably some minor change somewhere. I don't have access to trezor to continue testing for about 2-3 days, by which time the bounty will have expired. If you do not wish to extend it, that is fine, and I am just glad I was able to provide what should be a good starting point for someone else to implement it.

I'd like to thank everyone for their help and support.

**Comment by tinybike** [comment]
Hm, AFAIK we didn't intend for there to be a time limit on the bounty.  If there is one for some reason, please ignore it; we'll get it extended!

**Comment by meowingtwurtle** [comment]
Seems like yarn doesn't like the ethrpc version I have. Let me fix that.

**Comment by tomkysar** [comment]
cc: @meowingtwurtle does this work now? 🎉

**Comment by meowingtwurtle** [comment]
It works on my machine on Rinkeby testnet...

**Comment by phoebemirman** [comment]
tested on a trezor on rinkeby network and could sign in and make withdraw and rep faucet transactions

**Comment by meowingtwurtle** [comment]
BE WARNED: does not work on private-net (including docker:spin-up) for slightly complicated reasons.

**BIP44:** Trezor demands a reference to an account using the BIP44 standard (BIP being Bitcoin Improvement Proposal). As far as I can tell, BIP44 has no method for designating accounts for a privat network. This means we have to tell Trezor to use an account for one of: testnet, ETH, ETC, and it has an associated  chain id probably pre-programmed.

**The Issue:** Trezor accepts a chain id parameter in the call to sign a transaction. We can try two things (both end up failing on a private net): pass chain id of network that we say we are using, or pass chain id of network we are actually communicating with. The first option fails when we submit the transaction to our Ethereum node because the transaction chain id does not match the chain id of the network, causing a rejected transaction. The second option (giving Trezor chain id of actual network) also fails. This is likely because the Trezor has hard-coded chain ids for each of the valid Ethereum networks and returns the corresponding `v` parameter for that network. This discrepancy may cause failure in ecrecover & address derivation to return the incorrect result, leading to rejection of transaction.

**Comment by phoebemirman** [comment]
tested this again and connecting, rep faucet, withdraw still work

**Pull request merged**
