### PR TITLE
more templates

### PR DESCRIPTION
**Pull request by bthaile**
more templates
entertainment
finance
politics (us and world)
crypto

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🍦

 This link will always point to this PR's latest changes: https://peek.run/0elhzx3

**Review by phoebemirman — CHANGES_REQUESTED** [review]
whats this "on" thing?

Screen Shot 2019-10-11 at 3 40 03 PM

**Comment by bthaile** [comment]
we need a new input for DATEYEAR needs to be a date picker just the day

**Comment by bthaile** [comment]
Templates are good, imo

**Review by phoebemirman — APPROVED** [review]

**Pull request merged**
