### PR TITLE
Add percentage scalar invalid

### PR DESCRIPTION
**Pull request by bthaile**
addresses <https://github.com/AugurProject/augur/issues/5554>

For Scalar Invalid outcome order form will show `Percentage` input for user to input. 
The price will be calculated behind the scenes. 
total order value is read-only.

Same for market creation pre-liquidity. 

other minor fixes
template 'single player' should have been 'single horse'
fixed issue in zeroX orders when outcome doesn't have orders but is checked. 
small fix to convert exp helper

To test:
create Scalar market 100 to 200 price range or 10 to 20 something easily divisible. Then test order form for Invalid outcome

added error message dealing with percentage instead of price
image

fixed conversion from percentage to price
image

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🏅
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/2n5hxzv**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2020-01-16 at 6 01 12 PM
Screen Shot 2020-01-16 at 6 01 01 PM


seeing these issues: still getting quantity error, should say price for the other error and it is a quantity of 1?

**Comment by bthaile** [comment]
those are errors because of the tickSize divisible contract issue. 
def an issue, but not caused by this PR

**Review by JohnDanz — APPROVED** [review]

**Review by phoebemirman — APPROVED** [review]

**Review by JohnDanz — APPROVED** [review]

**Comment by bthaile** [comment]
combined on other PR

**Pull request closed without merging**
