### PR TITLE
added 14 extra pixels to the description's height

### PR DESCRIPTION
**Pull request by bconfortin**
I wasn't sure if I should just display the text in the bottom or if I should also add that same amount of pixels to the height of the card. I did the latter.

https://github.com/augurproject/augur/issues/3674

### CODE REVIEW

**Comment by bthaile** [comment]
Add the url to the github tix in the tix description.

**Comment by bthaile** [comment]
We have a design in figma to go off of. Missed adding a link. Can do that when at computer

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🧡

 This link will always point to this PR's latest changes: https://peek.run/xjlhkv0

**Review by bthaile — APPROVED** [review]
lgtm

**Pull request merged**
