### PR TITLE
finish updating styles for outcomes list on mobile

### LINKED ISSUE #4995: Design QA: Trading Page Mobile - Outcomes
Design: https://www.figma.com/file/fLWVwmanAwetVZbujQquEi/Market-Page?node-id=136%3A8112

Updates to the way outcomes are displayed on mobile

- [ ] Add in outcome column

- [ ] Check updates to type sizes and styles

- [ ] Check spacing 

- [ ] Allow outcome to go onto 2 lines remaining centred in row

- [ ] Add Ellipsis if longer

### PR DESCRIPTION
**Pull request by phoebemirman**
closes https://github.com/AugurProject/augur/issues/4995

### CODE REVIEW

**Review by bthaile — COMMENTED** [review]
Lgtm

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 💚
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/r9zh0en**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
long outcomes are not ellipsing on mobile. 

image


desktop
image

**Review by bthaile — CHANGES_REQUESTED** [review]
long outcomes should ellipse on mobile

**Comment by phoebemirman** [comment]
are you sure you were on the right branch?
Screen Shot 2019-12-11 at 10 42 24 AM

**Review by bthaile — APPROVED** [review]
looks good, I had a local issue.

**Pull request merged**
