### PR TITLE
Issue608

### PR DESCRIPTION
**Pull request by JohnDanz**
Check it out and double check my testing, linting and the coverage/build badges are now in the readme.

### CODE REVIEW

**Comment by thinkloop** [comment]
Hey John, looks really good! Few things:

Markets no longer load, having to do with something inside `./src/services/augurjs.js`. I think it may be because the underlying `augur.js` lib inside this `augurjs.js` file (confusing I know) checks for function type. Might get lucky changing the callbacks passed to the inner `augur.js` lib back to `function` rather than `()`. I think the top-level functions (anything not passed in to the `augur.js` lib) can remain the es6 style.

In package.json there is `jslint` (jshint) and `lint` (eslint) - are both functional or does one have to be removed? If so, there may be some related dev-packages and config files to remove too. 

the `lint` task in package.json is just `eslint` is it supposed to be run with `lint:all`?

When I run npm run coveralls I get an error at the end of what seems like a successful run:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v4.2.1/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v4.2.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'coverage' ]
2 info using npm@3.8.3
3 info using node@v4.2.1
4 verbose run-script [ 'precoverage', 'coverage', 'postcoverage' ]
5 info lifecycle augur-ui@2.0.0~precoverage: augur-ui@2.0.0
6 silly lifecycle augur-ui@2.0.0~precoverage: no script for precoverage, continuing
7 info lifecycle augur-ui@2.0.0~coverage: augur-ui@2.0.0
8 verbose lifecycle augur-ui@2.0.0~coverage: unsafe-perm in lifecycle true
9 verbose lifecycle augur-ui@2.0.0~coverage: PATH: /home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/workspace/node_modules/.bin:/home/ubuntu/.nvm/versions/node/v4.2.1/bin:/home/ubuntu/.nvm/versions/node/v4.2.1/bin:/usr/local/rvm/gems/ruby-2.2.2/bin:/usr/local/rvm/gems/ruby-2.2.2@global/bin:/usr/local/rvm/rubies/ruby-2.2.2/bin:/mnt/shared/bin:/home/ubuntu/workspace/node_modules/.bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/shared/sbin:/opt/gitl:/opt/go/bin:/mnt/shared/c9/app.nw/bin:/usr/local/rvm/bin
10 verbose lifecycle augur-ui@2.0.0~coverage: CWD: /home/ubuntu/workspace
11 silly lifecycle augur-ui@2.0.0~coverage: Args: [ '-c',
11 silly lifecycle   'istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage' ]
12 silly lifecycle augur-ui@2.0.0~coverage: Returned: code: 1  signal: null
13 info lifecycle augur-ui@2.0.0~coverage: Failed to exec coverage script
14 verbose stack Error: augur-ui@2.0.0 coverage: `istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid augur-ui@2.0.0
16 verbose cwd /home/ubuntu/workspace
17 error Linux 4.2.0-c9
18 error argv "/home/ubuntu/.nvm/versions/node/v4.2.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.2.1/bin/npm" "run" "coverage"
19 error node v4.2.1
20 error npm  v3.8.3
21 error code ELIFECYCLE
22 error augur-ui@2.0.0 coverage: `istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage`
22 error Exit status 1
23 error Failed at the augur-ui@2.0.0 coverage script 'istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the augur-ui package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs augur-ui
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls augur-ui
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by thinkloop** [comment]
John, my friend, I had to commit a big commit. I gave this a shot to merge in before.

**Comment by thinkloop** [comment]
John, my friend, had to push a commit. Tried to get this one in first.

**Comment by priecint** [comment]
Running `npm run lint:all` runs ok, too bad [it's not more verbose](https://github.com/eslint/eslint/issues/1101) - at first I was like: "does it even do anything?". But it's nice it doesn't show any errors, nice job :).

Do we need to specify the subfolders, why not just `eslint "src/**/*.js"`

@thinkloop about the functions: I tried
```
a = () => {}
typeof a
> "function"
b = function() {}
typeof b
> "function"
```
Could there be problem with `this`? Arrow funtions bind `this` already so it cannot be changed with `call`, `apply` or `bind`.

Running `npm run coverage` yields follwong:
```
{output from npm run test}
modules/transactions/selectors/transactions-totals.js
    ✓ should return the transaction totals for a blank state
    ✓ should properly return total info on transactions


  160 passing (2s)
  4 pending

=============================== Coverage summary ===============================
Statements   : 73.22% ( 1654/2259 )
Branches     : 57.38% ( 680/1185 )
Functions    : 63.26% ( 291/460 )
Lines        : 73.35% ( 1605/2188 )
================================================================================

/home/abc/work/augur/augur/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}

npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/home/abc/bin/node/node-v4.3.0-linux-x64/bin/node" "/home/abc/bin/node/node-v4.3.0-linux-x64/bin/npm" "run" "coverage"
npm ERR! node v4.3.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! augur-ui@2.0.0 coverage: `istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the augur-ui@2.0.0 coverage script 'istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the augur-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs augur-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls augur-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/abc/work/augur/augur/npm-debug.log
```

**Comment by JohnDanz** [comment]
So the coverage issue is because the repo token isn't an environment variable in the package. I have defined it as a n environment variable on travis-cli.org. This way when we push up a change to github and the travis job runs and defines the coverall repo and updates the coverage badge in the readme.

as for augurjs, I'm looking into why its not working now, i believe it has something to do with this as well, and that's where I'm going to start.

**Pull request merged**
