### PR TITLE
Zero x fixes

### PR DESCRIPTION
**Pull request by nuevoalex**
Fixes:

#5033 
#5119 
#5104

### CODE REVIEW

**Review by MicahZoltu — APPROVED** [review]
I believe this addresses the immediate issue.  I think it would be valuable to re-audit this contract though as when I was looking at it there were several attack avenues I didn't fully explore because this bug was certainly worse than the other avenues.

**Comment by epheph** [comment]
I believe this does fully resolve #5119 .

It _DOES_ patch the hole for re-entering via user-provided _exchange ~~, but the assetData does not need to refer to the ShareToken , so it can enter any contract that fulfills the ERC-1155 interface, and while doing so, can emit any message it wants.~~ <- this is not true, i had a bad model of what was encoded in AssetData . everything is 👍

**Comment by epheph** [comment]
It does patch #5033 .
For #5104 , anyone can still take ETH from ZeroXTrade, they just have to process an order of any size to do so. This might be "wontfix"

**Comment by epheph** [comment]
As discussed in discord, this line:

https://github.com/AugurProject/augur/blob/master/packages/augur-sdk/src/state/db/ZeroXOrders.ts#L15

and the offset lines near the bottom will require changes of `-=64`

**Review by epheph — APPROVED** [review]

**Pull request merged**
