### PR TITLE
pass in timezone if its available, pass it into timezone if its avail…

### PR DESCRIPTION
**Pull request by bthaile**
…able on parent component.

found bug with timezone not getting passed the value on newMarkets

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🤩

 This link will always point to this PR's latest changes: https://peek.run/o9ph75x

**Review by phoebemirman — CHANGES_REQUESTED** [review]
offset isn't being applied
Screen Shot 2019-10-10 at 10 20 47 PM

**Comment by bthaile** [comment]
removed the `useEffect` that was resetting timezone offset and offsetName. works now.

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2019-10-10 at 11 19 17 PM
getting this crash on review step

maybe cause end time is null? shouldn't happen when we add validations

**Comment by bthaile** [comment]
agreed, we'll need to add validations

**Review by phoebemirman — APPROVED** [review]

**Pull request merged**
