### PR TITLE
BIG WIP. DO NOT MERGE!

### PR DESCRIPTION
**Pull request by justinbarry**

### CODE REVIEW

**Comment by adrake33** [comment]
This pull request **introduces 2 alerts** when merging d63f3dd9dcfd3df8519b8db92e79b6dfd202663f into dfba8658ea96809e54e7d6b5c9fb446a9c105ed3 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur/rev/pr-d6c17e90c507449751c46a268e53cf2515fb82d1)

**new alerts:**

* 2 for Unused variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by adrake33** [comment]
This pull request **introduces 2 alerts** when merging ec9ba2bf6bbca64a41c037ae615892eb549e2573 into dfba8658ea96809e54e7d6b5c9fb446a9c105ed3 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur/rev/pr-663bd7fbeac3f9aca9452414f608c14fbd6783c2)

**new alerts:**

* 2 for Unused variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by adrake33** [comment]
This pull request **introduces 2 alerts** when merging ecd588521972b8a7adfbd29620feca59d77b9385 into dfba8658ea96809e54e7d6b5c9fb446a9c105ed3 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur/rev/pr-0b62e2b0fb669ec278b6382d088249827098bac7)

**new alerts:**

* 2 for Unused variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by adrake33** [comment]
This pull request **introduces 2 alerts** when merging c7a2a23d3c6f83c5665576a7399066e5a55bf6cc into dfba8658ea96809e54e7d6b5c9fb446a9c105ed3 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur/rev/pr-57a6c2f50276e4b28d1a9bebf6e8fc88152cc2df)

**new alerts:**

* 2 for Unused variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by adrake33** [comment]
This pull request **introduces 2 alerts** when merging fc36e1be28df399865dd14044c705e6fab65964a into dfba8658ea96809e54e7d6b5c9fb446a9c105ed3 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur/rev/pr-55fe3afc748bf54c56dc1f47933a091d7a60521c)

**new alerts:**

* 2 for Unused variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by tinybike** [comment]
@justinbarry is there a reason this needs to be a PR instead of just a branch?  If not, please close this PR until the branch is ready for review/merging.

**Comment by justinbarry** [comment]
@tinybike I _think_ this is the only way to get travisci to pay attention to me without modifying the config file. If I had modified the config file I'll offer even money it would accidentally merged to master.

**Comment by adrake33** [comment]
This pull request **introduces 1 alert** when merging 6336c20196aff6b3753e189e27686c90d321e9c5 into 26eba7d2dfab7d9556eca991b7ca64f7ed8203cd - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur/rev/pr-35932bc01c56014c7a78517a68310228d38f1b38)

**new alerts:**

* 1 for Unused variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by adrake33** [comment]
This pull request **introduces 1 alert** when merging 15e54314aeb70bd0878f9f6eee15cbc0ec96146c into 66bebf1ed75c2c2b0f367a0a9f1086690b8b1831 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur/rev/pr-4884d55559aaf2432a146bfe9f56e1e86d633a65)

**new alerts:**

* 1 for Unused variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by adrake33** [comment]
This pull request **introduces 1 alert** when merging 8241e293b628f086d3a2bf2a74c6ade2650701c2 into 66bebf1ed75c2c2b0f367a0a9f1086690b8b1831 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur/rev/pr-d47511f60b86b9789b4dfe0003cfae3f4554769a)

**new alerts:**

* 1 for Unused variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by adrake33** [comment]
Closing for now, since Travis is not stable enough.

**Pull request closed without merging**
