### PR TITLE
fixed binary markets only showing 2 outcomes on in-reporting market c…

### PR DESCRIPTION
**Pull request by bthaile**
…ards

fixes in-reporting market card. binary markets were only showing 2 outcomes with no `show more` 

image

fixed market cards awaiting next dispute window
image

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🥇

 This link will always point to this PR's latest changes: https://peek.run/o9phxkm

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2019-10-01 at 9 22 07 AM
getting this error clicking on scalar range outcome

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2019-10-01 at 1 27 39 PM
still getting this error when trying to click on the scalar range outcome

**Review by phoebemirman — CHANGES_REQUESTED** [review]
also typing values for one outcome is changing the values for all of them. see the REP column numbers have increased for my unselected outcomes 

Screen Shot 2019-10-01 at 1 29 20 PM
Screen Shot 2019-10-01 at 1 29 15 PM

**Review by phoebemirman — CHANGES_REQUESTED** [review]
also this happens when i am able to type in the scalar range outcome 

(the "enter a range..." text goes away, and so does the input box for it)

Screen Shot 2019-10-01 at 1 31 44 PM

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2019-10-01 at 5 24 36 PM
market list page is broken.
got this selecting filters

**Review by phoebemirman — DISMISSED** [review]

**Review by phoebemirman — APPROVED** [review]

**Comment by bthaile** [comment]
Good testing, thank @phoebemirman. all comments addressed. except scalar invalid outcome not activating submit button. created https://github.com/AugurProject/augur/issues/3974 and will work

**Pull request merged**
