### PR TITLE
toast fixes

### LINKED ISSUE #3637: failed alerts
- Filter out all pre signing errors from having failure alerts

### LINKED ISSUE #3840: toasts sometimes show for just a second
only set toast timer if there are toasts

### PR DESCRIPTION
**Pull request by phoebemirman**
closes https://github.com/AugurProject/augur/issues/3840

should be able to view multiple toasts after another 

closes https://github.com/AugurProject/augur/issues/3637

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🧡

 This link will always point to this PR's latest changes: https://peek.run/r9zhq54

**Review by bthaile — COMMENTED** [review]
not sure about adding this color. pinging @JohnDanz

**Comment by bthaile** [comment]
PR looks good.

**Review by bthaile — APPROVED** [review]
going with new red, design would need to get involved to not need the new red.

**Pull request merged**
