### PR TITLE
2561 signup working

### PR DESCRIPTION
**Pull request by stephensprinkle**

### CODE REVIEW

**Comment by tinybike** [comment]
Spinner looks good!  When I register, I get these errors in the console:
```
Uncaught TypeError: Cannot read property 'style' of null
    at PortfolioNavs.updatePortfolioNavHeight (eval at <anonymous> (main.957a588….js:5733), <anonymous>:63:24)
    at PortfolioNavs.updatePortfolioNavHeight (eval at <anonymous> (main.957a588….js:7948), <anonymous>:44:30)
    at later (eval at <anonymous> (main.957a588….js:738), <anonymous>:17:12)
```

**Comment by tinybike** [comment]
(The signup completes successfully in spite of that error though.)

**Comment by stephensprinkle** [comment]
Ok, taking a look into those errors now.

**Comment by stephensprinkle** [comment]
OK, that error should be fixed up now.

**Comment by tinybike** [comment]
Looks good!

**Pull request merged**
