### PR TITLE
Sort open orders in descending order, asks first

### PR DESCRIPTION
**Pull request by priecint**

### CODE REVIEW

**Comment by tinybike** [comment]
@priecint: this PR doesn't pass tests & the site doesn't load when I build with it -- I suspect it's not playing nice with the re-skinning PRs.  Can you update this PR?  (Please ping @stephensprinkle if you need help with this!)

**Comment by priecint** [comment]
Seems like it's alright again

**Comment by tinybike** [comment]
@priecint still not working.  Have you tried building and loading this?

**Comment by tinybike** [comment]
I get this error, doesn't even get past the loading screen:
```
components.jsx:29643 Uncaught TypeError: Cannot read property 'type' of undefined
```
Possibly this PR doesn't play nice with the new skinning updates?  Please update it as needed.

**Comment by stephensprinkle** [comment]
Hey — Just gave it a shot again against AURC master and it looks to be working per the spec description.  This branch does require a rebase against master however.  Screengrab below —
screen shot 2016-10-21 at 8 34 58 am 2

**Comment by priecint** [comment]
I was checking it against whatever AURC version specified in package.json

**Comment by tinybike** [comment]
@stephensprinkle thanks, it works fine now!  @priecint yes until augur/AURC repos are merged, got to make sure PRs updated to be consistent with the latest npm build.

**Pull request merged**
