### PR TITLE
Remove augur get network

### PR DESCRIPTION
**Pull request by bthaile**
remove all uses of `augur.rpc.getNetworkID()` add checks for connection.isConnected before being able to call getNetworkId() from contractCalls.

remove augur constants put them in UI constants for the time being. In the future they can move to SDK.

https://github.com/augurproject/augur/issues/1983

### CODE REVIEW

**Review by andrewdamelio — COMMENTED** [review]
Doesn't look like accountType is getting set for MetaMask.

**Comment by bthaile** [comment]
Changed constant to metaMask. See if that does the trick

**Review by bthaile — COMMENTED** [review]
Lgtm

**Review by andrewdamelio — APPROVED** [review]
LGTM some minor lint issues

**Pull request merged**
