### PR TITLE
Robert/trade unifier

### PR DESCRIPTION
**Pull request by robert-e-davidson3**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 😀
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/1rehowl**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Review by justinbarry — APPROVED** [review]
LGTM

**Review by andrewdamelio — CHANGES_REQUESTED** [review]
@robert-e-davidson3 UI needs to be updated alongside theses changes are the UI won't be able to make trades -- seeing this error on featurepeek.

image

**Comment by robert-e-davidson3** [comment]
> @robert-e-davidson3 UI needs to be updated alongside theses changes are the UI won't be able to make trades -- seeing this error on featurepeek.
> 
> image

The API changes shouldn't be breaking. I loaded up featurepeek but didn't get that error. What are your repro steps?

**Comment by robert-e-davidson3** [comment]
When looking into the bug from featurepeek I saw we needed to handle error reporting. I made a change in the UI for that.

**Comment by andrewdamelio** [comment]
> > @robert-e-davidson3 UI needs to be updated alongside theses changes are the UI won't be able to make trades -- seeing this error on featurepeek.
> > image
> 
> The API changes shouldn't be breaking. I loaded up featurepeek but didn't get that error. What are your repro steps?

@robert-e-davidson3 see below for REPO steps
REPO STEPS: 
- Login with Gnosis or NOT Gnosis (doesn't matter)
- Going to a trading page
- Try and place a trade
- Nothing will happen in the UI -- console error

**Comment by robert-e-davidson3** [comment]
> > > @robert-e-davidson3 UI needs to be updated alongside theses changes are the UI won't be able to make trades -- seeing this error on featurepeek.
> > > image
> > 
> > 
> > The API changes shouldn't be breaking. I loaded up featurepeek but didn't get that error. What are your repro steps?
> 
> @robert-e-davidson3 see below for REPO steps
> REPO STEPS:
> 
> * Login with Gnosis or NOT Gnosis (doesn't matter)
> * Going to a trading page
> * Try and place a trade
> * Nothing will happen in the UI -- console error

I introduced a typo in Wrapper.tsx :/ it's fixed now. When featurepeek updates, can you take another look?

**Review by andrewdamelio — APPROVED** [review]
looks good now!

**Pull request merged**
