### PR TITLE
655 positions reskin

### PR DESCRIPTION
**Pull request by stephensprinkle**

### CODE REVIEW

**Comment by tinybike** [comment]
Hmm, positions aren't updating dynamically -- I have to refresh to see the positions listed.

**Comment by stephensprinkle** [comment]
K, let me take a look.

**Comment by tinybike** [comment]
Unethical thumbs-down should be red!
screenshot_2017-03-28_12-15-14

**Comment by stephensprinkle** [comment]
Ah, misspelled that class!  Just pushed a fix.

**Comment by stephensprinkle** [comment]
Hang on, this change didn’t quite resolve things well.

**Comment by stephensprinkle** [comment]
OK, the fix looks to be working properly.  Let me just update the tests + the PR should be GTG again.

**Comment by tinybike** [comment]
Not 100% sure if this is due to a change on this branch, but the transactions history is now loading in an infinite loop (and pegging my CPU)...

**Comment by tinybike** [comment]
Update: it appears to also be infinitely reloading the order book for one particular market (0xdf4e99d24efb76b9d0b7ea389b8add7ddf260242f39407eac15638969224b1d5).

**Comment by tinybike** [comment]
Update x2: I can't reliably reproduce the infinite reload, and am not sure it's caused by this PR, so going to go ahead and merge this.  Looking good btw! :grin:

**Pull request merged**
