### PR TITLE
add scalar info to core properties

### PR DESCRIPTION
**Pull request by phoebemirman**
https://github.com/AugurProject/augur/issues/5983

### CODE REVIEW

**Comment by bthaile** [comment]
Verify that reporting form modal looks ok.

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 👨‍🎤
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/exohg65**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by phoebemirman** [comment]
looks good to me

**Review by bthaile — APPROVED** [review]
lgtm

**Pull request merged**
