### PR TITLE
fix trading tutorial issues

### PR DESCRIPTION
**Pull request by phoebemirman**
https://github.com/AugurProject/augur/issues/5712

also fix bug where help icon would show twice during load

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 💎
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/zr5h5jk**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Review by bthaile — APPROVED** [review]
lgtm

**Comment by bthaile** [comment]
Is max profit and max loss suppose to have values?

image

**Review by bthaile — APPROVED** [review]
one question, PR looks good. approving

**Pull request merged**
