### PR TITLE
new input, Update Over/Under and Point Spread templates

### LINKED ISSUE #4763: Special behavior regarding connected pickers in templates for Yes/No:
So for Yes/No
If a user selects the team first, the event displayed can only show the correct possible event
For example: MLB: Will the [Team] win the [Year] [Event]?
And Someone selects The NY Yankees....The event in the dropdown can only be American League Championship Series Or World Series (National League should not be a choice in this example bc the Yankees play in the American League)

This is for any sport where selecting a team to win a championship/finals type of event 

So MLB, NHL, NBA, NFL, NCAA BB, NCAA FB

### LINKED ISSUE #4844: Templates: Baseball, first yes no template
dropdown dep in market question

image

depending on the event user selects only certain lists of teams is available. 
      value: 'American League Championship Series',
      value: 'National League Championship Series',
      value: 'World Series',

use `export const BASEBALL_EVENT_DEP_TEAMS` to determine dropdowns

need validation for market question values are correct.

### PR DESCRIPTION
**Pull request by bthaile**
closes <https://github.com/augurproject/augur/issues/4763>
closes <https://github.com/augurproject/augur/issues/4844>
baseball YesNo market. 

default view, user needs to select an Event before selecting a team
image

when user selects event
image

If use changes the Event the TEAM dropdown gets cleared and replaced with new list.

### CODE REVIEW

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2019-11-21 at 2 02 23 PM
getting this error when clicking next and nothing is selected in the dropdowns

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2019-11-21 at 2 04 53 PM
Screen Shot 2019-11-21 at 2 04 39 PM

team name not displaying / not being cleared out

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🆒
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/5m3h1en**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
tried to go `next` to test validation, no failures and get correct validation messages

image

**Comment by bthaile** [comment]
PR looks good, all the code is there

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2019-11-22 at 8 23 38 AM
event dropdown is missing validation msg

**Comment by bthaile** [comment]
I can fix that on next PR. I want to get these changes in for chwy to test. User still cant. Progress. Until the select event then team

**Review by phoebemirman — APPROVED** [review]

**Pull request merged**
