### PR TITLE
Trade-form-updates

### PR DESCRIPTION
**Pull request by JohnDanz**
Updated trade ticket to more closely match the updated mocks. refactored a bit during that process.

https://github.com/AugurProject/augur/issues/4937
https://github.com/AugurProject/augur/issues/4938

Might also close some of the issues outlined here but I'll double check when I review tickets later
https://github.com/AugurProject/augur/issues/4968

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🍭
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/xjlh09o**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
on this PR
image


Order Form should have button at bottom
image

**Comment by bthaile** [comment]
on this PR
Screen Shot 2019-12-02 at 6 01 17 PM


there should be a message that doesn't allow user to add cross order book
image

**Review by bthaile — CHANGES_REQUESTED** [review]
testing order form for market creation there are issues. Too many change, will cause regression.

**Comment by bthaile** [comment]
I recommend just addressing the tickets and not doing large refactors.

**Review by bthaile — APPROVED** [review]
works and lgtm

**Pull request merged**
