### PR TITLE
streamlines docker builds

### PR DESCRIPTION
**Pull request by petong**

### CODE REVIEW

**Review by bthaile — APPROVED** [review]
Looks good,prob need another pair of eyes as well.

**Comment by petong** [comment]
augur-core needs a few changes, working on them now

**Review by bthaile — APPROVED** [review]
Lgtm

**Comment by petong** [comment]
I went over all the details with scott, we should be good

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
