### PR TITLE
[auth] Create keystore should use button instead of checkbox

### PR DESCRIPTION
**Pull request by kennsippell**
https://app.clubhouse.io/augur/story/4563/keystore-transition-check-to-next-button

### CODE REVIEW

**Comment by kennsippell** [comment]
This is what exists today:
image

The result of this proposed change:
image
image

List of proposed changes:
1. Once a valid passphrase is entered, I propose a single visually grouped cta. Currently a combination of disabling & hiding reveals the next call to action in two separate areas. 
1. The current UI cannot be completed on mobile. The `accept` button cannot be viewed on the screen. Stacking the elements vertically instead of horizontally seems like a straightforward fix. There is enough vertical real-estate to stay above the fold (no scrolling)
1. The "Accept and Connect" call to action was a checkbox, that functioned like a button. I just made it a button.
1. After clicking "accept and connect", notify the user that they will be redirected to the markets page.

**Comment by kennsippell** [comment]
In general, I wonder why this keystore functionality is supported at all inside augur. Seems like a questionable recommendation to be giving users along-side secure alternatives. High potential for key loss (enough that we feel compelled to alert the user in this ui), Micah mentioned security issues with having the browser know your sk.

**Comment by stephensprinkle** [comment]
@sharkcrayon — Pinging you to give a peek @ @kennsippell’s suggestions.

**Comment by sharkcrayon** [comment]
@kennsippell I'd like to do a combination of what you put together and the original mocks. First, let's make the mocked design work better responsively:

1. Get rid of the anomalous left-hand padding.
2. On `.Keystore__form` remove `flex: 3` and add `width: calc(100% - 300px)`
3. On `.Keystore__instruction` remove `flex: 2` and add `width: 300px`

You may run into a bug with `calc` where, IIRC, `calc(100% - 300px)` in our code is output as something like `-200px` in the browser. Something is going wrong in our preprocessing, and it seemed like the "math" was being done on the numbers themselves while ignoring their different measurement types. I'm hoping that's magically not happening now...but it may be something you or @stephensprinkle have to dig into for this layout, because I don't see a better way than using `calc` here.

Set a breakpoint for 1180px so that the layout you came up with is used for all screen sizes less than 1180px.

**Comment by sharkcrayon** [comment]
Also, keep your change from "Accept & Connect" from a checkbox to a button.

**Comment by kennsippell** [comment]
< 1100
image

>1100
image

mobile
image

**Pull request merged**
