### PR TITLE
mobile updates

### PR DESCRIPTION
**Pull request by phoebemirman**
https://github.com/AugurProject/augur/issues/5013

### CODE REVIEW

**Review by bthaile — APPROVED** [review]
lgtm

**Review by bthaile — CHANGES_REQUESTED** [review]
some market creation form format issues. see comment with screen shots

**Comment by bthaile** [comment]
Current issues, 
1. there is a compile error. in form.tsx
image


2. format is off
PR
image


on V2
image

**Review by bthaile — APPROVED** [review]
Lgtm

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). ✨
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/5m3hoep**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Pull request merged**
