### PR TITLE
Filled orders updates

### PR DESCRIPTION
**Pull request by JohnDanz**
fixes est fee tooltip among style tweaks for labels and updating the view etherscan transaction button

https://github.com/AugurProject/augur/issues/4968

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🏄‍♂️
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/654h6w7**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
Is this PR suppose to address alignment issues in Portfolio?

image


image

**Comment by bthaile** [comment]
seeing this issue for My Fills on market trading page

image

**Review by phoebemirman — APPROVED** [review]

**Comment by bthaile** [comment]
on trading page values are drifting on positions
image

**Comment by bthaile** [comment]
That is a really long button to view etherscan transaction.
image

**Review by bthaile — APPROVED** [review]
I assume styling issue will be fixed in another PR.

**Pull request merged**
