### PR TITLE
ethereumjs-ledger@2.1.5

### PR DESCRIPTION
**Pull request by tinybike**
Resolves [ch13056](https://app.clubhouse.io/augur/story/13056/bump-ethereumjs-ledger-version)

@JohnDanz can you please verify that Ledger works with this version bump?

### CODE REVIEW

**Comment by bthaile** [comment]
We’ll also need to build augur-app and test ledger when we get out local signed cert solution in place.

**Comment by JohnDanz** [comment]
Tom has mentioned this is actually fixed in another branch, I'm going to defer to him and retest when he gives me the OK.

**Comment by tinybike** [comment]
@bthaile which branch has the fixes that @JohnDanz referred to above?  Have these already been merged to master, or no?

**Comment by JohnDanz** [comment]
I'm still having trouble with my ledger, however i want to bump the version and according to our clubhouse issue both tom and phoebe were able to use theres. https://app.clubhouse.io/augur/story/13160/re-test-ledger-integration

**Pull request merged**
