### PR TITLE
4060 add forking banner to app tsx

### PR DESCRIPTION
**Pull request by bconfortin**
Added the forking-banner to App.tsx

Desktop
Mobile

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 💛

 This link will always point to this PR's latest changes: https://peek.run/vv2h29w

**Review by bthaile — APPROVED** [review]
I didn't see any side effects on regular non-forking website. good to go.

**Review by bthaile — COMMENTED** [review]
actually not sure about the banner showing up over the top bar.

**Review by bthaile — CHANGES_REQUESTED** [review]
@phoebemirman  has a suggestion on placement in App.tsx

**Review by bthaile — APPROVED** [review]
verified that reg non-forking UI looks fine, approving

**Pull request merged**
