### PR TITLE
run augurSdk.connect() before listening for events

### PR DESCRIPTION
**Pull request by robert-e-davidson3**

### CODE REVIEW

**Comment by robert-e-davidson3** [comment]
@Mergifyio backport dev

**Comment by robert-e-davidson3** [comment]
I tested this. It works.

**Review by pgebheim — APPROVED** [review]

**Review by pgebheim — CHANGES_REQUESTED** [review]
This is wrong -- we want the ui to listen to the events before doing the connect.

That is what triggers the various startup events.

**Comment by robert-e-davidson3** [comment]
> This is wrong -- we want the ui to listen to the events before doing the connect.
> 
> That is what triggers the various startup events.

to clarify: this works in the websocket connector mode but breaks the normal UI mode

**Comment by robert-e-davidson3** [comment]
Actually that does not seem to be a problem but since this is a high risk change, we're going to sit on it until after launch.

**Review by pgebheim — APPROVED** [review]

**Pull request merged**
