### PR TITLE
fix reporting on scalar markets including invalid outcome

### LINKED ISSUE #3549: Reporting page: scalar market reporting error
image

Getting this error when:
 * inputting valid scalar value between min and max Price.
 * adding additional stake when initially reporting

### PR DESCRIPTION
**Pull request by bthaile**
fixes https://github.com/augurproject/augur/issues/3549

old util helper was using v1 logic instead of v2 logic to convert from outcome to payout numerators

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 💚

 This link will always point to this PR's latest changes: https://peek.run/p37hpgr

**Comment by robert-e-davidson3** [comment]
I find `isInvalid` confusing because validity is a pretty broad concept. I prefer `invalidOutcome`.

**Review by robert-e-davidson3 — APPROVED** [review]
lgtm

**Comment by bthaile** [comment]
IsInvalid is a  V1 common term.

**Pull request merged**
