### PR TITLE
only allow fridays for movie templates

### PR DESCRIPTION
**Pull request by phoebemirman**
https://github.com/AugurProject/augur/issues/5648

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🎖
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/vv2hkzv**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
need to update templates-template.ts for post market creation shield. 
so that if user creates a market using template through API and they put the opening day on date other than friday, the market should not get the shield. 
Need to update docs as well.

**Review by bthaile — CHANGES_REQUESTED** [review]
more work is needed to verify template movie open date is on friday for post market creation.

**Review by bthaile — APPROVED** [review]
Lgtm

**Review by bthaile — APPROVED** [review]
Lgtm

**Pull request merged**
