### PR TITLE
deployment writes to local-*.json files instead of the permanent records

### PR DESCRIPTION
**Pull request by robert-e-davidson3**
I also did a bit of cleanup but did NOT remove any networks from addresses.json and other files.

For future deployments to non-local networks (mainnet, kovan, etc), the deployer will need to manually overwrite the json files we commit to git (ex: upload-block-numbers.json).

### CODE REVIEW

**Comment by bthaile** [comment]
I assume you tested cranking up docker:geth and deploying contracts and verifying that addresses.json doesn't get updated?

**Comment by robert-e-davidson3** [comment]
> I assume you tested cranking up docker:geth and deploying contracts and verifying that addresses.json doesn't get updated?

I had tested it with ganache. I went ahead and tested docker:geth as well to the same good result.

**Comment by bthaile** [comment]
Excellent

**Review by bthaile — APPROVED** [review]
Lgtm

**Review by nuevoalex — APPROVED** [review]
cool

**Pull request merged**
