### PR TITLE
make common component for date and time selector pieces

### LINKED ISSUE #4074: MC: Templates Estimated start date and time
- **start date and time**
   - Components used
      - Uses date picker component
      - Uses time picker component
      - Uses timezone component (defaults to users current timezone) 
   - When user enters the date and time, a box will appear below showing the users time converted to UTC0 (see [here] (https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=434%3A408) for example)

<https://www.figma.com/file/IpIAYVQPeQfuT5TTUboQpo4S/Market-creation?node-id=923%3A358>

image

### PR DESCRIPTION
**Pull request by phoebemirman**
closes https://github.com/AugurProject/augur/issues/4074

also cleaned up the template form a bit

going to wait until template object is ready to put the estimated start time on the form because only some templates have it

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🏆

 This link will always point to this PR's latest changes: https://peek.run/kq3h2je

**Comment by bthaile** [comment]
auto complete doesn't work

image

**Comment by bthaile** [comment]
and the text doesn't clear so the user can type their search value

image

**Review by bthaile — CHANGES_REQUESTED** [review]
need some fixes

**Review by bthaile — APPROVED** [review]
works well

**Pull request merged**
