### PR TITLE
Layout adjusted to meet the layout

### PR DESCRIPTION
**Pull request by bconfortin**
https://github.com/AugurProject/augur/issues/4060

Layout adjusted to meet the mocks both in desktop and mobile

Mobile
Desktop

Missing TODO:
> banner needs to show up on all pages.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 💙

 This link will always point to this PR's latest changes: https://peek.run/qo0h4l2

**Review by bthaile — APPROVED** [review]
lgtm

**Comment by bthaile** [comment]
```
Missing TODO:

banner needs to show up on all pages.
```

does this mean, will do in another PR?

**Comment by bconfortin** [comment]
> ```
> Missing TODO:
> 
> banner needs to show up on all pages.
> ```
> 
> does this mean, will do in another PR?

@bthaile Yeah, doing it right now

**Pull request merged**
