### PR TITLE
Fix outcome mobile

### PR DESCRIPTION
**Pull request by bthaile**
fixing issue where outcome get bunched up

Screen Shot 2019-10-07 at 5 34 08 PM

Screen Shot 2019-10-07 at 5 32 48 PM

fixed
image

### CODE REVIEW

**Review by phoebemirman — CHANGES_REQUESTED** [review]
messes up desktop
Screen Shot 2019-10-07 at 3 37 04 PM

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2019-10-07 at 3 37 48 PM
still looks off on tablet

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 😁

 This link will always point to this PR's latest changes: https://peek.run/g7ohvk4

**Review by phoebemirman — APPROVED** [review]
looks good on tablet. small mobile and desktop still a bit off margin wise

**Pull request merged**
