### PR TITLE
Added invalid market rules to info icon besides invalid outcome

### LINKED ISSUE #5468: Invalid outcome tooltip
Design:
https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=3226%3A0

For desktop mouseover we want to display the full rules.

For mobile on tap of the tooltip icon we will need to bring up a modal displaying the rules

### PR DESCRIPTION
**Pull request by bconfortin**
Closes #5468

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🏆
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/w9jhno5**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
getting 2 (?) icons next to Invalid, is that correct?

image

**Comment by joeykrug** [comment]
seems wrong re two ??

**Comment by bthaile** [comment]
It should be getting fixed. @bconfortin  is aware

**Comment by bconfortin** [comment]
Fixing it. Style priority issues @joeykrug

**Review by bthaile — APPROVED** [review]
lgtm

**Pull request merged**
