### PR TITLE
Solidify types in a few reducers/Fix category filter

### LINKED ISSUE #2438: Exception thrown when providing category to getMarkets getter
```
asyncToGenerator.js?fcee:6 Uncaught (in promise) Error: Invalid request object: Invalid value null supplied to : (({ universe: string } & PartialType<{ creator: string, category: string, search: string, reportingState: (string | Array<string>), disputeWindow: string, designatedReporter: string, maxFee: string, hasOrders: boolean }>) & PartialType<{ sortBy: string, isSortDescending: boolean, limit: number, offset: number }>)/category: (string | undefined)/0: string,Invalid value null supplied to : (({ universe: string } & PartialType<{ creator: string, category: string, search: string, reportingState: (string | Array<string>), disputeWindow: string, designatedReporter: string, maxFee: string, hasOrders: boolean }>) & PartialType<{ sortBy: string, isSortDescending: boolean, limit: number, offset: number }>)/category: (string | undefined)/1: undefined
    at Router.eval (Router.ts?0ee1:63)
    at step (Router.js:32)
    at Object.eval [as next] (Router.js:13)
    at eval (Router.js:7)
    at new Promise (<anonymous>)
    at __awaiter (Router.js:3)
    at Router.route (Router.ts?0ee1:49)
    at API.eval (API.ts?8f68:21)
    at step (API.js:32)
    at Object.eval [as next] (API.js:13)
```

### PR DESCRIPTION
**Pull request by justinbarry**
closes #2438, #2440, #2437

### CODE REVIEW

**Comment by bthaile** [comment]
image


get this error after logging in.

**Comment by pgebheim** [comment]
@justinbarry @bthaile -- Is this relevant anymore?

constants.ts now has a bunch of conflicts just due to " and ' -- did this code get in through another path?

**Comment by bthaile** [comment]
@justinbarry was making headway on this recently

**Comment by justinbarry** [comment]
Moved types stuff to another PR. Closing this.

**Pull request closed without merging**
