### PR TITLE
round dai balance to 4 and other fixes to get T-F-T started

### LINKED ISSUE #2986: Trading order form flickers
Trading order form changes from logged in to logged out and back to logged in.

Look in either sign in with MM code or in init-augur. There is code that auto logs out the user.

### LINKED ISSUE #3056: available funds is rounding ####.00000
need to have 4 digit precision to display in top bar. Look in contractCalls.ts

### LINKED ISSUE #3058: user can't log out
auto login won't allow user to logout.

### LINKED ISSUE #3060: MC: user has enough ETH but gets Error.
User has plenty of ETH to pay for gas but MC indicates the user doesn't have enough.

image

### LINKED ISSUE #3062: MC: End time is wrong on on preview
image

endTime needs to be a timestamp.

### PR DESCRIPTION
**Pull request by bthaile**
…ner not in component so order form doesn't flicker

fixes https://github.com/AugurProject/augur/issues/3056
fixes https://github.com/augurproject/augur/issues/2986
fixes https://github.com/AugurProject/augur/issues/3058
fixes https://github.com/augurproject/augur/issues/3060
fixes https://github.com/augurproject/augur/issues/3062

fixed variable name, said eth should be dai

### CODE REVIEW

**Comment by justinbarry** [comment]
Market creation isn't loading on this branch. Cannot confirm the last two issues are fixed.

**Comment by bthaile** [comment]
Does v2.augur.net load?
Also what format isnt loading? Desktop, tablet, mobile. I’m wondering what is up?

**Comment by justinbarry** [comment]
Desktop with the metamask wallet. Doesn't seem to want to load on v2.augur.net.

**Review by justinbarry — APPROVED** [review]
Lgtm

**Pull request merged**
