### PR TITLE
Integrate `getReportingFees` function into UI

### PR DESCRIPTION
**Pull request by adrake33**
[Clubhouse Story](https://app.clubhouse.io/augur/story/8240/integrate-augur-node-api-getreportingfees-function-to-claim-all-section-of-portfolio-reporting-page)

This PR replaces some previous hard-coding to use the new augur-node function `getReportingFees`. I also renamed some of the files from things like `load-claimable-fees.js` to `get-reporting-fees.js`.

Some of the unit tests didn't really make sense to have once `getReportingFees` was being used, so I removed them.

## Submitter checklist
- [x] Test covering functionality added/fixed in
- Check the linked story includes the following:
  - [x] Steps to reproduce
  - [ ] Screenshot (If applicable)

## Reviewer Checklist
- [ ] Test/lint pass

### CODE REVIEW

**Comment by bthaile** [comment]
@adrake can you add repro steps or best way to test to the ch task?

**Comment by bthaile** [comment]
@adrake thanks for the info, I'll review your PR

**Comment by bthaile** [comment]
Getting error when clicking 'Claim' in augur.js claim-reporting-fees.js. `p.onSuccess(result)` onSuccess is undefined.

I pulled in `adrake/ch8914/update-claimreportingfees-function-to-accept` to augur.js and linked to ui. Also didn't see where onSuccess method was passed into `claimReportingFees`

As a side note, not sure why there is a pass through augur.js to get data from augur-node (getReportingFees)

**Comment by adrake33** [comment]
@bthaile This PR should work with the current master branch of augur.js. It's just ch8915 that depends on ch8914. Using adrake/ch8914/update-claimreportingfees-function-to-accept will cause things to break when used with adrake/ch8240/integrate-augur-node-api-getreportingfees.

I'm not sure how to call an augur-node function directly from the UI code. Do you have an example so I don't have to go through augur.js?

**Comment by adrake33** [comment]
@bthaile Never mind -- I found an example in get-dispute-info.js. I'll update my code to use augurNode directly.

**Comment by adrake33** [comment]
@bthaile Ok, the code has been updated to use augurNode. I also fixed a copy/paste error where the `redeemableContracts` array is being generated.

**Comment by bthaile** [comment]
so this should work against augur.js master, I merged your augur.js PR.

**Comment by adrake33** [comment]
I reverted your merge from augur.js because this PR won't work with adrake/ch8914/update-claimreportingfees-function-to-accept.  This PR uses the old input format when calling `claimReportingFees`.

**Pull request merged**
