### PR TITLE
6481 add portfolio report

### PR DESCRIPTION
**Pull request by bthaile**
added reporting to portfolio sub nav. roughed out component view and container view.

### CODE REVIEW

**Comment by sharkcrayon** [comment]
@bthaile Can you remove the stuff you added to the Portfolio:Reporting page? We have other stories for all the stuff that's going to be added there.

**Comment by bthaile** [comment]
Yes, I'll remove the contents of portfolio reporting page.

**Comment by sharkcrayon** [comment]
@bthaile Feel free to remove everything but the "Portfolio: Reporting" title. (Also, the title text needs to be changed from "Portfolio: Report" to "Portfolio: Reporting".)

**Comment by bthaile** [comment]
@sharkcrayon made changes based on your request, should be gtg.

**Comment by sharkcrayon** [comment]
@bthaile One more thing to remove: the "Export Data" link in the top right.

**Pull request merged**
