### PR TITLE
recordMarketShareTokens does not return bool

### PR DESCRIPTION
**Pull request by robert-e-davidson3**

### CODE REVIEW

**Comment by robert-e-davidson3** [comment]
WIP until I get the ABI updated. Taking longer than I expected because I need to install a newer solc.

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). ⭐️
 To view it, be sure to [join Augur Project](https://dashboard.featurepeek.com/login) on FeaturePeek.

 This link will always point to this PR's latest changes: https://peek.run/exohqlq

**Comment by robert-e-davidson3** [comment]
No ABI change. I assume because it's a private function.

**Review by nuevoalex — APPROVED** [review]
👍

**Pull request merged**
