### PR TITLE
show errorModal on trading failures

### PR DESCRIPTION
**Pull request by andrewdamelio**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🍪
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/l74hq2l**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
no ticket associated with this effort. Did @Chwy5 or @joeykrug say to do this?

**Comment by andrewdamelio** [comment]
@bthaile 

@pgebheim requested some feedback in the order form - since we show nothing on errors currently.  Maybe just temporary,  until we are more stable?

**Review by bthaile — APPROVED** [review]
this is used for debugging, will get removed for release

**Pull request merged**
