### PR TITLE
1281 aurc merge

### PR DESCRIPTION
**Pull request by stephensprinkle**

### CODE REVIEW

**Comment by tinybike** [comment]
Epic PR

**Comment by stephensprinkle** [comment]
Ha, it is!  Basically all commits post Nov 30th are the relevant ones, the rest is AURC’s log.

**Comment by tinybike** [comment]
Getting this error from `yarn build`:
```
(1281-aurc-merge) jack@vent:~/src/augur$ yarn build
yarn build v0.17.10
$ node scripts/build.js 
module.js:442
    throw err;
    ^

Error: Cannot find module 'webpack-merge'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jack/src/augur/webpack.config.js:4:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by tinybike** [comment]
```
(1281-aurc-merge) jack@vent:~/src/augur$ npm install --save-dev webpack-merge
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "webpack-merge"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.6

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jack/src/augur/npm-debug.log
```

**Comment by tinybike** [comment]
```
/home/jack/src/augur/src/utils/list-words-under-length.js
  1:1  warning  Prefer default export  import/prefer-default-export
```
Many of these warnings from tests -- is there a reason for preferring default export?  Personally I find named functions somewhat more convenient (b/c they can easily be grepped as "function nameOfFunction" throughout the codebase) but I'm open.

**Comment by tinybike** [comment]
Hm, transaction descriptions not getting set properly it looks like --

screenshot - 12132016 - 11 11 12 pm

**Comment by tinybike** [comment]
Getting this error when I try and create a market:
```
DateTime.js?c71e:98 Uncaught (in promise) TypeError: Cannot read property 'isValid' of null
    at Object.getStateFromProps (eval at 1282 (1.fcd34b2….js:103), <anonymous>:89:85)
    at Object.getInitialState (eval at 1282 (1.fcd34b2….js:103), <anonymous>:64:20)
    at new eval (eval at <anonymous> (main.047d46f….js:2287), <anonymous>:653:54)
    at eval (eval at <anonymous> (main.047d46f….js:6167), <anonymous>:137:24)
    at instantiate (eval at <anonymous> (main.047d46f….js:6167), <anonymous>:145:9)
    at Datetime (eval at proxyClass (eval at <anonymous> (main.047d46f….js:6167)), <anonymous>:4:17)
    at eval (eval at <anonymous> (main.047d46f….js:1853), <anonymous>:297:18)
    at measureLifeCyclePerf (eval at <anonymous> (main.047d46f….js:1853), <anonymous>:77:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (eval at <anonymous> (main.047d46f….js:1853), <anonymous>:296:16)
    at ReactCompositeComponentWrapper._constructComponent (eval at <anonymous> (main.047d46f….js:1853), <anonymous>:282:21)
```

**Comment by tinybike** [comment]
Got rid of the deprecated update timer stuff, still getting this error:
```
index.js?1484:28 Uncaught TypeError: Cannot read property 'updater' of null
    at forceUpdateIfPending (eval at <anonymous> (main.224a644….js:6112), <anonymous>:28:33)
    at traverseRenderedChildren (eval at <anonymous> (main.224a644….js:6112), <anonymous>:6:3)
    at traverseRenderedChildren (eval at <anonymous> (main.224a644….js:6112), <anonymous>:13:9)
    at traverseRenderedChildren (eval at <anonymous> (main.224a644….js:6112), <anonymous>:9:5)
    at traverseRenderedChildren (eval at <anonymous> (main.224a644….js:6112), <anonymous>:13:9)
    at traverseRenderedChildren (eval at <anonymous> (main.224a644….js:6112), <anonymous>:13:9)
    at traverseRenderedChildren (eval at <anonymous> (main.224a644….js:6112), <anonymous>:9:5)
    at traverseRenderedChildren (eval at <anonymous> (main.224a644….js:6112), <anonymous>:13:9)
    at traverseRenderedChildren (eval at <anonymous> (main.224a644….js:6112), <anonymous>:9:5)
    at traverseRenderedChildren (eval at <anonymous> (main.224a644….js:6112), <anonymous>:13:9)
```

**Comment by tinybike** [comment]
Ok, think this is all fixed up -- merging!

**Pull request merged**
