### PR TITLE
Market view responsive

### PR DESCRIPTION
**Pull request by JohnDanz**
buckle up. lots of changes.

https://github.com/AugurProject/augur/issues/5692
https://github.com/AugurProject/augur/issues/5620
https://github.com/AugurProject/augur/issues/4572
https://github.com/AugurProject/augur/issues/5050

### CODE REVIEW

**Review by phoebemirman — CHANGES_REQUESTED** [review]
seeing this when expanding the right column and then the tables

Screen Shot 2020-01-31 at 5 01 43 PM
Screen Shot 2020-01-31 at 5 01 39 PM
Screen Shot 2020-01-31 at 5 01 34 PM

**Comment by bthaile** [comment]
tablet port view. also doesn't scroll
image

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🙌
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/zr5h55k**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by pgebheim** [comment]
Adding `work-in-progress` appears to break some things,

**Review by phoebemirman — CHANGES_REQUESTED** [review]
looks good just seeing this 
Screen Shot 2020-02-03 at 9 46 44 AM

should order book fill length of the screen?

**Review by phoebemirman — APPROVED** [review]

**Review by bthaile — APPROVED** [review]
lgtm, iPro layout has been fixed

**Pull request merged**
