### PR TITLE
Bruno/quadbox refactor

### PR DESCRIPTION
**Pull request by bconfortin**
**It might be better to get inside this branch and check it in the IDE**
Big PR since it has the quadbox/filterbox/filterswitchbox refactor.

#7403

### CODE REVIEW

**Review by phoebemirman — CHANGES_REQUESTED** [review]
filled and open orders are missing their dropdown. also when you expand a collapsed box, I think it is supposed to make the two boxes share the space, not have it take up the whole space. similar to how trading page works.

**Comment by phoebemirman** [comment]
seeing this as well 
image

**Comment by phoebemirman** [comment]
also dropdown should be hidden when search is on 
image

also this market is missing my unsigned orders alert for some reason

also when you click on the search box X, the text is supposed to be cleared

**Comment by phoebemirman** [comment]
can we add market counts here 
image

favorites have an arrow that doesn't do anything
image

**Review by JohnDanz — CHANGES_REQUESTED** [review]
Screen Shot 2020-09-04 at 8 08 14 AM


need to have some space between these on mobile

**Comment by JohnDanz** [comment]
Screen Shot 2020-09-04 at 8 10 49 AM

the search bar should fill the rest of the space, so we have only a small ~8px gap between filter and search, should grow when clicked to fill the entire top area and cover the filters until unfocused.

**Comment by JohnDanz** [comment]
Screen Shot 2020-09-04 at 8 11 03 AM

similar issue here as the above, in this case, the search bar should cover the entire top section since there is no filter option and it should be aligned with the spacing of the content below.

**Comment by phoebemirman** [comment]
toggling is very broken in portfolio 
looks like this:
Screen Shot 2020-09-04 at 10 12 44 AM

then when I click the top quad expand it becomes this:
Screen Shot 2020-09-04 at 10 12 49 AM
so there is no way to even out the space

**Comment by phoebemirman** [comment]
this is broken as well. shows in reporting as open
Screen Shot 2020-09-04 at 10 16 19 AM

**Review by phoebemirman — CHANGES_REQUESTED** [review]
spacing not matching original:
Screen Shot 2020-09-04 at 10 38 00 AM

looking off:
Screen Shot 2020-09-04 at 10 36 27 AM

**Review by JohnDanz — APPROVED** [review]

**Review by phoebemirman — APPROVED** [review]

**Pull request merged**
