### PR TITLE
Robert/flash improvements

### LINKED ISSUE #7064: SDK Server Broken: ZeroX.addOrdersAsync
When trying to place a trade in the UI while the SDK server is enabled and running, this error occurs in the console:

```
ZeroX.js:245 TypeError: Cannot read property 'addOrdersAsync' of undefined
    at ZeroX.addOrders (ZeroX.js:241)
    at ZeroX.placeOnChainOrders (ZeroX.js:167)
    at async ZeroX.placeOnChainTrade (ZeroX.js:130)
addOrders @ ZeroX.js:245
placeOnChainOrders @ ZeroX.js:167
async function (async)
placeOnChainOrders @ ZeroX.js:164
placeOnChainTrade @ ZeroX.js:130
async function (async)
placeOnChainTrade @ ZeroX.js:121
placeOnChainTrade @ Trade.js:43
placeTrade @ Trade.js:28
placeTrade @ Augur.js:349
placeTrade @ contractCalls.ts:621
eval @ place-market-trade.ts:34
eval @ index.js:9
eval @ index.ts:22
onSubmitPlaceTrade @ wrapper.ts:67
placeMarketTrade @ wrapper.tsx:191
action @ wrapper.tsx:243
onClick @ buttons.tsx:103
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:389
executeDispatchesInOrder @ react-dom.development.js:411
executeDispatchesAndRelease @ react-dom.development.js:3278
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3287
forEachAccumulated @ react-dom.development.js:3259
runEventsInBatch @ react-dom.development.js:3304
runExtractedPluginEventsInBatch @ react-dom.development.js:3514
handleTopLevel @ react-dom.development.js:3558
batchedEventUpdates$1 @ react-dom.development.js:21871
batchedEventUpdates @ react-dom.development.js:795
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 8 more frames
place-market-trade.ts:35 TypeError: Cannot read property 'rejected' of undefined
    at ZeroX.placeOnChainOrders (ZeroX.js:168)
    at async ZeroX.placeOnChainTrade (ZeroX.js:130)
```

It's likely the problem is that the default configuration, and the configuration we expect in production, disables zerox.rpc while enabling zerox.mesh. The mesh is not runnable in nodejs, which is what the SDK server runs under.

So the fix is to have the sdk server script (or the code it calls) alter the configuration to enable zero.rpc if zerox.mesh is enabled. However that still won't work in production if the default zerox.rpc endpoint is used so some more thought is probably necessary.

### PR DESCRIPTION
**Pull request by robert-e-davidson3**

### CODE REVIEW

**Review by bthaile — COMMENTED** [review]
flash scripts that I tried look good and a lot faster.

**Comment by pgebheim** [comment]
Fixed SDK server + other zeroX issues here related to #7064 here https://github.com/AugurProject/augur/pull/6990/commits/9a45d706d2e2332ef6316fbda3400d1f647d1910

**Review by pgebheim — APPROVED** [review]

**Comment by pgebheim** [comment]
@mergifyio merge

**Comment by pgebheim** [comment]
@Mergifyio update

**Pull request merged**
