### PR TITLE
ZeroX orders will be sycned from RPC before bulk sync.

### PR DESCRIPTION
**Pull request by pgebheim**
This still doesn't fix the case where the mesh allows order-getting,
since in that case we'll need to do the `sync()` call after the mesh
is initialized, but that can just be done on the DB directly.

### CODE REVIEW

**Review by bthaile — APPROVED** [review]
lgtm, is ZeroX:Ready did seem to be used anyway

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🔥
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/kq3h7z3**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by pgebheim** [comment]
> lgtm, is ZeroX:Ready did seem to be used anyway

Yeah, it wasn't. We still technically need to defer sync until the mesh is around if we're going to be using the mesh.getMeshOrders functionality.

**Review by bthaile — APPROVED** [review]
lgtm

**Pull request merged**
