### PR TITLE
templates: Add new `USER_DROPDOWN_OUTCOME ` dropdown

### LINKED ISSUE #4767: Add additional template for NCAA Basketball
Need to be added under NCAA Basketball Multiple Choice:

NCAA BB: Which college basketball team will win the [Men's/Women's] [Year] D1 National Championship?

Outcomes Must Include:
Other (Field)

the outcome list is all College BB teams within the Picker List

### PR DESCRIPTION
**Pull request by bthaile**
closes <https://github.com/augurproject/augur/issues/4767>
adds another way user can add outcomes to a template. This outcome dropdown doesn't depend on market question dropdown.
new TemplateInputType `USER_DROPDOWN_OUTCOME`

image

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 😄
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/r9zh2kg**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Review by phoebemirman — CHANGES_REQUESTED** [review]
error msg missing
Screen Shot 2019-11-14 at 5 33 10 PM

**Comment by bthaile** [comment]
separate PR to add error message for estimate date time
<https://github.com/AugurProject/augur/pull/4777>

**Review by bthaile — COMMENTED** [review]
Lgtm, nice one

**Review by phoebemirman — APPROVED** [review]

**Comment by bthaile** [comment]
resolved conflict, will have to regen templates

**Pull request merged**
