### PR TITLE
uniswap middleware/UI work 

### PR DESCRIPTION
**Pull request by andrewdamelio**
#4358

 - Wire up REP rate
- add contractCalls/Processing button for swapExactTokensForTokens, swapETHForExactTokens
 - UI updates 
- Add Funds Rep (DAI/ETH -> REP)
- Add Funds Dai (REP/ETH -> DAI)

@bthaile ready for review now

### CODE REVIEW

**Comment by andrewdamelio** [comment]
@nuevoalex can you take a look at https://github.com/AugurProject/augur/pull/7195/commits/6d7a96ac2e11c8751f99774643a206a88f6aa478

**Comment by pgebheim** [comment]
@mergifyio rebase

**Comment by bthaile** [comment]
convert looks like a button but doesn't do anything
image

**Comment by andrewdamelio** [comment]
> convert looks like a button but doesn't do anything
> image

It use to be a toggle between pool & swap. I can remove it since is not a toggle anymore!

**Comment by bthaile** [comment]
confirm button has wrong color
image

**Comment by bthaile** [comment]
same style issue with failed button
image

**Comment by andrewdamelio** [comment]
@bthaile

**Review by bthaile — APPROVED** [review]
lgtm

**Pull request merged**
