### PR TITLE
1928 topic req

### PR DESCRIPTION
**Pull request by stephensprinkle**

### CODE REVIEW

**Comment by tinybike** [comment]
When I try to navigate to the market after creating a new market (by clicking on it in the transaction display), I get the following error:
```
Uncaught Error: abi.unfork failed (bad input): "0x0000000000000000000000000000000000000000000000000000000undefined"
    at Object.unfork (eval at <anonymous> (main.1599293….js:113), <anonymous>:218:15)
    at Object.packageRequest (eval at <anonymous> (main.1599293….js:871), <anonymous>:1255:37)
    at Object.invoke (eval at <anonymous> (main.1599293….js:871), <anonymous>:1299:25)
    at Object.fire (eval at <anonymous> (main.1599293….js:871), <anonymous>:1439:10)
    at Augur.fire (eval at <anonymous> (main.1599293….js:5262), <anonymous>:16:21)
    at Augur.batchGetMarketInfo (eval at <anonymous> (main.1599293….js:5108), <anonymous>:270:17)
    at loader (eval at <anonymous> (main.1599293….js:540), <anonymous>:31:64)
    at eval (eval at <anonymous> (main.1599293….js:540), <anonymous>:49:7)
    at eval (eval at <anonymous> (vendor.fa9fb0d….js:1423), <anonymous>:11:18)
    at eval (eval at <anonymous> (main.1599293….js:60), <anonymous>:20:14)
    at dispatch (eval at <anonymous> (vendor.fa9fb0d….js:2132), <anonymous>:55:18)
```

**Comment by tinybike** [comment]
I don't think the topic is getting properly set -- when I create a new market, its topic is never added to the topics list, even after a refresh.

**Comment by stephensprinkle** [comment]
@tinybike — Make sure it’s not just getting sliced — we currently only display the top 50 topics.  

I’ll take a look @ the transaction issue.

**Comment by stephensprinkle** [comment]
Nuked my other comment — I’ll double check that the topic is being set as the first tag.  

Also going to take a look @ the transactions link issue.

**Comment by stephensprinkle** [comment]
Can confirm that topics are being set correctly during market creation + topic is returned correctly when loading markets.  

Looks like topics with 0 volume are excluded from the topics returned from the topics returned from `getTopicsInfoChunked`.

**Pull request merged**
