### PR TITLE
Create bug report template

### PR DESCRIPTION
**Pull request by adrake33**
This will create a new button on the Issues page for filing a bug report and should help ensure we have more relevant info when a bug gets filed.

### CODE REVIEW

**Review by bthaile — COMMENTED** [review]
Mention iser has to login to see version information. 

Thoughts on button for feature request.

**Comment by adrake33** [comment]
Ah good point about having to be logged in. Yeah, I was also planning to create one for Feature Requests but hadn't gotten around to it yet.

**Review by bthaile — APPROVED** [review]
Lgtm

**Comment by adrake33** [comment]
Actually, since we're using ZenHub now, I don't think there's really a need to redirect all v1 tickets to the augur repo anymore. ZenHub can pull in issues from multiple repos, so we should use this template for v1 bugs and create a different template for v2 bugs later. Will close this for now and move it to the augur-app repo.

**Pull request closed without merging**
