### PR TITLE
add warp sync market to dr section

### PR DESCRIPTION
**Pull request by bthaile**
https://github.com/AugurProject/augur/issues/8514
when warp sync market is in designated reporting show in DR section so anyone can report on it. 

image

@Mergifyio backport dev

### CODE REVIEW

**Review by nuevoalex — APPROVED** [review]
🐐

**Comment by bthaile** [comment]
@Mergifyio update

**Comment by bthaile** [comment]
@Mergifyio update

**Comment by bthaile** [comment]
@Mergifyio update

**Comment by bthaile** [comment]
@Mergifyio update

**Pull request merged**
