### PR TITLE
Update augursdk.ts

### PR DESCRIPTION
**Pull request by joeykrug**

### CODE REVIEW

**Comment by bthaile** [comment]
I don't think we will get orders if rpc is set to false. based on my testing.

**Comment by bthaile** [comment]
got 0 ZeroX orders with rpc: false

with rpc: true I at least get orders in db.
image

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 😀
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/qo0h7nv**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Review by bthaile — APPROVED** [review]
lgtm, based on discussion in UI channel we need to get order propagating via mesh

**Pull request merged**
