### PR TITLE
inner nav padding fix

### PR DESCRIPTION
**Pull request by phoebemirman**
https://github.com/AugurProject/augur/issues/4632

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🔮
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/36whnvr**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
feature peek, saw some padding issues with market list section.

image

**Comment by bthaile** [comment]
image

**Comment by phoebemirman** [comment]
thats not related to this change but ill put a fix on this branch

**Review by bthaile — APPROVED** [review]
lgtm, issue found isn't related to this PR

**Pull request merged**
