### PR TITLE
Removed unused and deprecated auth methods

### PR DESCRIPTION
**Pull request by tinybike**
Resolves [ch7010] in combination with https://github.com/AugurProject/augur.js/pull/253

### CODE REVIEW

**Comment by tinybike** [comment]
Good catch @justinbarry.  Actually now that I'm looking more closely at the tests, the mocks used are very out-of-date (beyond just what changed in this PR); updating them now.

**Comment by tinybike** [comment]
@justinbarry Tests, mocks, etc. should be ready-to-go now.

**Comment by tinybike** [comment]
@justinbarry Good catch re: glob, is this ready for merge or you want to give it a final once-over?

**Comment by justinbarry** [comment]
@tinybike I went over it last night and everything looked great.

**Pull request merged**
