### PR TITLE
Change shape of data returned by getMarkets

### LINKED ISSUE #3067: Update shape of data returned by getMarkets
Shape of data should be:
{
      markets: objects[],
      meta: {},
      filteredOutCount: 0, 
      marketCount: 0,
}
(Hard-code `meta`, `filteredOutCount`, & `marketCount` for now.)

Also update tests accordingly and implement `limit` & `offset` params.

### PR DESCRIPTION
**Pull request by adrake33**
Closes #3067.

### CODE REVIEW

**Comment by bthaile** [comment]
Any changes needed in the UI?

**Comment by adrake33** [comment]
Yes, getMarkets used to return just an array of market IDs. Now those market IDs will need to be obtained from the `markets` array in the object that's returned. The `markets` array is an array of objects containing data about each market.

**Comment by bthaile** [comment]
So are you saying that if this PR was merged in it would break the UI?

**Comment by adrake33** [comment]
Yeah, I'm also noticing that it breaks some things in Flash. I'll work on updating the UI calls to this function too as part of this PR.

**Review by bthaile — APPROVED** [review]
works and lgtm

**Pull request merged**
