### PR TITLE
6401-Participation-Modal-errors

### PR DESCRIPTION
**Pull request by JohnDanz**
adds error checking/pagination to the participate modal, adds the participate review modal. Updated modal-view to add the little X to close button to the top right corner of the view. Left in place old logic for big close button for uport and ledger modals.

[Clubhouse Story](https://app.clubhouse.io/augur/story/6401/pts-modal-error-checking-and-pagination)
and
[Clubhouse Story 2](https://app.clubhouse.io/augur/story/6404/pts-modal-review-view)

## Submitter checklist
- [x] Test covering functionality added/fixed in
- Check the linked story includes the following:
  - [x] Steps to reproduce
  - [x] Screenshot (If applicable)

## Reviewer Checklist
- [ ] Test/lint pass 
- [ ] Post merge, story marked complete

### CODE REVIEW

**Comment by JohnDanz** [comment]
Steps to reproduce can be found on ticket, but essentially they are the same as the last few tickets with Modal Participate. 

Login with an account that has > 0 REP
Navigate to Reporting > Dispute
click the `PARTICIPATE` button on the top right.

Entering a value <= 0 should be an error, entering a value > your_total_rep should result in an error. 

Clicking on review should bring you to a review page, Note the functionality is Not Yet Implemented and is coming in a later ticket.

**Comment by justinbarry** [comment]
Also, @JohnDanz how do I "un-review" this transaction? (Back button, cancel button, etc.)
screen shot 2018-03-09 at 12 01 22 pm

**Comment by JohnDanz** [comment]
In the mocks, there is currently no `back` button or `un-review` as you asked for, so i didn't include one. I would imagine we want a `back` button. 

As for the enter issue, good catch, i didn't account for this and will make sure this has the desired effect.

**Comment by justinbarry** [comment]
@JohnDanz Since you are already in there..... Does the pencil icon have any functionality?

**Comment by JohnDanz** [comment]
No it doesn't, are you suggesting I make it functional and have it return to the previous page?

**Comment by JohnDanz** [comment]
I'll add a back button instead.

**Comment by justinbarry** [comment]
Enter key works as expected as does new back button.

screen shot 2018-03-09 at 2 08 56 pm

**Comment by justinbarry** [comment]
More things:
1. Please add autocomplete="off" to the form to prevent the above dropdown.
2. Clicking max button when input isn't focused put it in this state:
screen shot 2018-03-09 at 2 10 18 pm

**Pull request merged**
