### PR TITLE
Use commander for `flash` for betterness

### PR DESCRIPTION
**Pull request by pgebheim**
argparse was terrible and unsupported.

I switched to `commander` which gives actual useful help text and isn't so obtuse.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). ⭐️
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/0elhlre**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
yarn flash-util generate-templates

doesn't work. get this error

image

**Review by bthaile — CHANGES_REQUESTED** [review]
got error running `yarn flash-util ...` 

forgot to run `yarn`

**Review by bthaile — APPROVED** [review]
works with happy path, 

doesn't verify args though, so script runs and fails and doesn't inform the user they forgot args.

**Review by bthaile — APPROVED** [review]
lgtm

**Review by bthaile — APPROVED** [review]
this seems to work, lgtm

**Pull request merged**
