### PR TITLE
Animated graph background integration.

### PR DESCRIPTION
**Pull request by smallfx**
Hardware accelerated + responsive. 📈✨

### CODE REVIEW

**Comment by stephensprinkle** [comment]
In further testing, it’s looks to be related to the window size as exhibited here: https://www.youtube.com/watch?v=PXGx53aFfOk

**Comment by stephensprinkle** [comment]
NOTE — just waiting on the p5 warning messages resolution, then this should be good to merge.

**Comment by stephensprinkle** [comment]
@smallfx — I’m going ahead and closing this for the time being.

**Comment by smallfx** [comment]
So, modifying the P5 library didn't work as I expected after research... though having read all of the renderer code, I figured out that it had some slightly unexpected requirements when in "immediate mode" (just drawing primitives directly). Seems like line shapes need `.fill()` set for every `.shapeBegin()`, which I don't even think they use (should be using `.stroke()` color). Anyway, setting it for each shape seems to have no detrimental effect on performance.

**Comment by stephensprinkle** [comment]
🎉

**Comment by stephensprinkle** [comment]
Thanks for the extra detail!

**Pull request merged**
