### PR TITLE
Moved Yes Outcome to the first position

### LINKED ISSUE #4642: Yes/No order on the Market cards is backwards
Yes needs to be listed as the first outcome on the Market Cards, then No, then Invalid

### PR DESCRIPTION
**Pull request by bconfortin**
Fixes https://github.com/augurproject/augur/issues/4642

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 😀

 This link will always point to this PR's latest changes: https://peek.run/n5xho6k

**Comment by bthaile** [comment]
as you mentioned and I verified. 
categorical markets with 2 outcomes do get reversed(), need a condition for YES_NO

**Review by bthaile — CHANGES_REQUESTED** [review]
add check for YES_NO markets before reversing

**Review by bthaile — APPROVED** [review]
lgtm

**Pull request merged**
