### PR TITLE
move logic from UI to SDK to get user data when user synced is completed

### PR DESCRIPTION
**Pull request by bthaile**
Moved user aggregated login data to SDK. 

fixed `undefined` showing on portfolio page
image

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). ⭐️

 This link will always point to this PR's latest changes: https://peek.run/m96h6pr

**Review by andrewdamelio — COMMENTED** [review]
Look good!
noticed the below error when I'm signed in

image

**Comment by bthaile** [comment]
~~I'm not able to repro the error above. If `getUserAccountData` didn't have account then there would be many more errors like that. I think it's coming from log-handlers. I'll address in a different PR when I can repro.~~

I see a use case where the error could be produced. If the user doesn't have any trades. fixed

**Review by andrewdamelio — APPROVED** [review]
fixed!

**Pull request merged**
