### PR TITLE
Update-order-book

### PR DESCRIPTION
**Pull request by JohnDanz**
https://github.com/AugurProject/augur/issues/4703

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 💖
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/kq3h5rg**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Review by phoebemirman — CHANGES_REQUESTED** [review]
orders aren't centered vertically 

Screen Shot 2019-12-11 at 1 05 45 PM

**Review by phoebemirman — CHANGES_REQUESTED** [review]
bottom borders are off when hovering

Screen Shot 2019-12-11 at 1 28 14 PM

**Review by phoebemirman — CHANGES_REQUESTED** [review]
top order is cut off and it wont let me scroll 

Screen Shot 2019-12-11 at 1 54 25 PM


my quantity column only has 8px padding to the right of it - other columns aren't lining up either with their headers

Screen Shot 2019-12-11 at 1 55 09 PM

also still seeing the underline issue

**Review by phoebemirman — APPROVED** [review]

**Pull request merged**
