### PR TITLE
Candle filling

### PR DESCRIPTION
**Pull request by JohnDanz**
https://github.com/AugurProject/augur/issues/4739

added "empty" buckets to show no change in price. Updated highlighted width to always match the width of the candle/volume bar highlighted.

### CODE REVIEW

**Comment by bthaile** [comment]
weird that the middle candle doesn't give volume

image

**Comment by bthaile** [comment]
only 2 trades but there is 3 candles.

image

**Review by bthaile — CHANGES_REQUESTED** [review]
looks like there is a phantom trading in the chart. If it's a place holder to indicate no trades then it needs to be grey/white and not highlight when user mouses over.

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). ⚡️
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/n5xho3w**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
image

missing grey dash indicating no trade was made at 20:00
image

**Comment by bthaile** [comment]
larger length of time with tradeless hours. I would expect grey dash at previous hours close on tradeless hours
image

**Review by bconfortin — APPROVED** [review]

**Review by bthaile — APPROVED** [review]
good

**Pull request merged**
