### PR TITLE
Add `docker-compose pull` script to package.json

### PR DESCRIPTION
**Pull request by justinbarry**
[Clubhouse Story](https://app.clubhouse.io/augur/story/8971)

### CODE REVIEW

**Comment by bthaile** [comment]
It should pull the image if not already pulled, right?

**Comment by justinbarry** [comment]
Yes.

**Comment by bthaile** [comment]
Why do we need this docker:spin-pull command, I'm a bit confused.

**Comment by justinbarry** [comment]
@epheph Is the augur-node image tag stable?

**Comment by justinbarry** [comment]
@bthaile :dev moves as augur-node is updated. We need this to pull newer images in.

**Comment by bthaile** [comment]
I see what you are talking about. Also, I've seen the docker:spin-up fail because the images were taking too long to download. We need to build the pull into the spin-up and not have separate commands.

**Comment by bthaile** [comment]
@justinbarry What do you think about my changes?

**Pull request merged**
