### PR TITLE
Pg/derived new block

### LINKED ISSUE #5368: Reporting ends soon Notifications and designated reporting on reporting pg do not go away after market is reported on
I reported on this market through reporting pg.  The notification I have doesnt go away (needs to)
The "Report" button remains enabled and the countdown timer keeps showing for me on the reporting pg (makes me think I need to report again), should remove timer countdown to the DR after Designated reports and should disable the report button to the dr

### PR DESCRIPTION
**Pull request by pgebheim**
this should fix <https://github.com/AugurProject/augur/issues/5368>

### CODE REVIEW

**Comment by pgebheim** [comment]
Partial fix, works just like yours but removes the extra eth_call from the MarketDB

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🌶
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/2n5h6w9**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Review by pgebheim — COMMENTED** [review]
Simple, love it.

**Review by bthaile — APPROVED** [review]
lgtm

**Pull request merged**
