### PR TITLE
don't allow user to put more than 32 characters in outcome

### LINKED ISSUE #4868: Templates and custom: limit outcome length
outcomes can only be 32 characters, or the market creation will fail. 

add validation checks for outcome length for custom and template form

### PR DESCRIPTION
**Pull request by bthaile**
fixes https://github.com/augurproject/augur/issues/4868

image

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🤙
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/n5xhqxx**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Review by phoebemirman — CHANGES_REQUESTED** [review]
not seeing the error here
Screen Shot 2019-11-26 at 3 21 23 PM

**Comment by bthaile** [comment]
there needs to be at least 2 outcomes first before length is tested.

**Comment by phoebemirman** [comment]
why?

**Comment by bthaile** [comment]
that's how the validation conditions are setup. 
if there is not 2 outcomes then it returns that error.
if there are 2 or more then other validation conditions are tested. 

I can refactor and clean up outcome validations.

**Review by phoebemirman — APPROVED** [review]

**Comment by phoebemirman** [comment]
ok seems fine for now then

**Pull request merged**
