### PR TITLE
fix type issue when using max liquidity spread filter

### PR DESCRIPTION
**Pull request by bthaile**
fixes type error in code, also was seeing  console error.

image
 

image

backend didn't like the string passed in for maxLiquiditySpread. it needed to be typed.

### CODE REVIEW

**Review by pgebheim — COMMENTED** [review]
Id split out that Union and make a med type and use that in both the interface as well as when casting it.

**Comment by bthaile** [comment]
Tried doing that I couldnt figure out the syntax. Help would greatly be appreciated

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🍕

 This link will always point to this PR's latest changes: https://peek.run/xjlhk55

**Review by pgebheim — APPROVED** [review]
Yes like that!

**Pull request merged**
