### PR TITLE
subtract gas price from max value in withdraw modal

### LINKED ISSUE #4986: withdraw modal: max button causes error
need to subtract transaction fee from DAI amount.  in the example below user has 200,000 DAI balance

### PR DESCRIPTION
**Pull request by phoebemirman**
closes https://github.com/AugurProject/augur/issues/4986

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🔮
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/r9zh0kk**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
just pressing MAX, get NaN

image

**Comment by bthaile** [comment]
with DAI balance
image

**Review by bthaile — CHANGES_REQUESTED** [review]
need to figure out why MAX is giving NaN

**Review by bthaile — APPROVED** [review]
works looks good

**Pull request merged**
