### PR TITLE
Add blank scalar dispute card

### LINKED ISSUE #3697: Disputing: Scalar card, add generic outcome
New scalar mock outcome so user can dispute 

https://www.figma.com/file/Do4qnkCNM8P7lwBmCdYZCS4X/Market-Cards?node-id=2543%3A471

### PR DESCRIPTION
**Pull request by bthaile**
image

fixes https://github.com/augurproject/augur/issues/3697

formatting is off, will be fixed as part of condensing market cards.

have form open to selected outcome
image

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🏅

 This link will always point to this PR's latest changes: https://peek.run/vv2hzj0

**Review by phoebemirman — COMMENTED** [review]
should we make it so when you click on that outcome the corresponding one is seleced in the modal? like how it works for the other outcomes

**Review by phoebemirman — APPROVED** [review]

**Comment by bthaile** [comment]
sounds like a good idea. how to select the outcome for a scalar?

**Comment by phoebemirman** [comment]
check out how the other ones work, probably need to use a constant instead of an id

**Pull request merged**
