### PR TITLE
Mobile tweaks to filters and sorting

### PR DESCRIPTION
**Pull request by bconfortin**
On mobile, when you click the filters/sorting, you now have to click on the "Apply" button in order to actually apply those.

### CODE REVIEW

**Review by bthaile — COMMENTED** [review]
looks good to me. I'd like @andrewdamelio  to take a peek at it.

**Review by andrewdamelio — CHANGES_REQUESTED** [review]
I noticed an issue when canceling a filter selection.

To Reproduce:
1) On Desktop view set all filters to All, url params will be ```spread=100&maxFee=1&templateFilter=all```
2) Now switch to mobile view and change the filters but don't click apply, click "X"
3) The page will crash due to the params being wrong, looks like they are getting jumbled up ```spread=hide&maxFee=100&templateFilter=1&showInvalid=all```


which is causing the below error

image

**Comment by bconfortin** [comment]
@andrewdamelio Thanks for catching that. Lack of attention on my part while copying/pasting variables.

**Review by andrewdamelio — APPROVED** [review]
LGTM now!

**Pull request merged**
