### PR TITLE
`Estimated schedule start time` gets its own line and use local time for templates and some clean up

### LINKED ISSUE #4688: Templates: move estimated scheduled start time to extraInfo
remove from market question, keep input. 

image

add `estimatedStartTime` as unix timestamp to extraInfo

in UI format market question with 
{description}
{estimatedStartTime}

Will The Team A win vs the Team B
Estimated schedule start time [Date;time}

### PR DESCRIPTION
**Pull request by bthaile**
closes <https://github.com/augurproject/augur/issues/4688> 
added timestamp for (DATETIME and ESTDATETIME) to input object in extraInfo that is sent in create market contract transaction.
broke out Estimated schedule start time to it's own line in market title.
use user's local time to display DATETIME and ESTDATETIME dates.

Screen Shot 2019-11-10 at 9 59 52 AM

Screen Shot 2019-11-10 at 9 47 28 AM

Screen Shot 2019-11-10 at 9 29 56 AM

Screen Shot 2019-11-10 at 9 28 56 AM

clean up from missing some resolution rules and added invalid rule to top of market creation form

in templates put estimated scheduled start time on its own line. remove from actual question
image

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 💚
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/5m3h37k**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2019-11-11 at 8 50 39 AM
title is missing from preview

**Review by phoebemirman — COMMENTED** [review]
Screen Shot 2019-11-11 at 8 52 23 AM
you are missing margin here between additional details and the title

**Review by phoebemirman — COMMENTED** [review]
why do these look different? they are both templates


Screen Shot 2019-11-11 at 8 54 03 AM

**Comment by bthaile** [comment]
they look different because those markets that include `estimated scheduled start time` were created before I made the changes to template data in market creation

**Comment by phoebemirman** [comment]
i just made the baltimore ravens vs atlanta falcons one though

**Comment by bthaile** [comment]
you created market doesn't have the template shield icon

**Review by phoebemirman — APPROVED** [review]

**Pull request merged**
