### PR TITLE
Category filter markets list v2

### LINKED ISSUE #3094: Remove `tags` from UI
tags are no longer used. They can be removed from the UI. Primary, secondary and tertiary categories are replacing tags

categories are listed at top of market card and are clickable to navigate the user to that category on market list page.

### PR DESCRIPTION
**Pull request by andrewdamelio**
closes #3094 #2863 

- Wired up Category filter to the loadMarkets call
- Removed old Category/Tag code
- Removed a bunch of unused code from App.tsx

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 💎

 This link will always point to this PR's latest changes: https://peek.run/m96hvxn

**Review by bthaile — COMMENTED** [review]
code lgtm, going to test it out.

**Review by phoebemirman — COMMENTED** [review]
Screen Shot 2019-08-27 at 4 23 26 PM
Screen Shot 2019-08-27 at 4 23 14 PM
why are these numbers different after clicking on the category?

it's also wrong for the crypto one, says one but has two

**Comment by bthaile** [comment]
could be error in data from getter, def needs to be run to ground

**Comment by andrewdamelio** [comment]
@bthaile @phoebemirman 
> why are these numbers different after clicking on the category?

Assuming we should only be getting back category counts for CURRENT filtered results this seems to make sense. When you click through to a specific category you are making a more specific search so you should get back more results for that selected category if they exist.

I can add the loading so we don’t see that flash from one number to another.

> https://recordit.co/bCxKz2PrTM

**Comment by bthaile** [comment]
The category counts should include all the markets in the category and subcategories. 

For example, if Sports has 2 and Tennis has 2 then the meta data should have Sports as having 4 markets. If the data isn't coming back like this from the getter we have a bug.

**Review by bthaile — APPROVED** [review]
lgtm

**Pull request merged**
