### PR TITLE
fix category nav for real this time. Checked side category menu and c…

### PR DESCRIPTION
**Pull request by bthaile**
…licking on market card sub category and leaf category with testing back button. seems to be working well.

https://github.com/AugurProject/augur/issues/7510

added efficiency to not refresh market list page if user logs in and hasn't changed default filters. Same on logout.

### CODE REVIEW

**Review by andrewdamelio — CHANGES_REQUESTED** [review]
looks like you can get into a funky state if you keep clicking parent-child on the side menu
image

To reproduce:
(Using the side menu filters)
- click Medical
- click The World
- click Medical
- click The World
- Should see `http://localhost:8080/#!/markets?category=medical%2Cthe%20world%2Cthe%20world`
image

**Review by andrewdamelio — CHANGES_REQUESTED** [review]
Another issue i just found... see video here -> https://recordit.co/4uB1yubKL3

If you click the second category (bitcoin) it goes to bitcoin instead of Crypto-Bitcoin

**Comment by bthaile** [comment]
what is the URL? after clicking the market card category?

**Comment by andrewdamelio** [comment]
> what is the URL? after clicking the market card category?

1st click, clicking on `Btceur (Crypto - Bitfinex)` -> http://localhost:8080/#!/markets?category=crypto%2Cbitcoin%2Cbtceur%20(crypto%20-%20bitfinex)

2nd click, clicking on bitcoin -> http://localhost:8080/#!/markets?category=crypto%2Cbitcoin

3rd click, clicking on bitcoin again -> http://localhost:8080/#!/markets?category=bitcoin

**Comment by bthaile** [comment]
PR updated

**Review by andrewdamelio — APPROVED** [review]
Nice

**Pull request merged**
