### PR TITLE
fixed dai balance issues

### PR DESCRIPTION
**Pull request by joeykrug**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://dashboard.featurepeek.com). 🔮
Your deployment will be kept up-to-date with this pull request's latest changes.

**https://peek.run/zr5h5n9**

-------

*Please read [our docs](https://docs.featurepeek.com/configuring-peek-yml/) for more configuration details.*

**Comment by bthaile** [comment]
how do I repro the issue this PR fixes?

**Comment by joeykrug** [comment]
Inspect totalcost property on confirm.tsx when trading, eventually it’ll be randomly wrong and let you trade even though you don’t have the money. Dai cost never is wrong

**Review by bthaile — APPROVED** [review]
lgtm

**Pull request merged**
