### PR TITLE
upgrade packages

### PR DESCRIPTION
**Pull request by epheph**

### CODE REVIEW

**Comment by adrake33** [comment]
Yarn package for uport-connect is failing in Travis

**Comment by epheph** [comment]
```error An unexpected error occurred: "https://registry.yarnpkg.com/uport-connect: Request \"https://registry.yarnpkg.com/uport-connect\" returned a 403".
```

some intermittent error during build?

**Comment by epheph** [comment]
image

**Comment by epheph** [comment]
Yup, broken for everyone, the internet is horrified

https://twitter.com/search?q=registry.yarnpkg.com&src=typd

image

**Comment by adrake33** [comment]
Yay, good times!

**Pull request merged**
