### PR TITLE
Add categories

### LINKED ISSUE #4360: Templates: add user ability to nav to third category
some templates will have category -> secondary -> third category.

change get-templates to return templates for 3rd categories

### LINKED ISSUE #4361: Add 2nd Category and 3rd Category to Market creation templates
Add 2nd Category to crypto:

BTC, ETH, LTC,

Add 3rd Category for Basketball

NBA, NCAA

Add 3rd Category for Football

NFL, NCAA

### LINKED ISSUE #4377: template: need to activate sub-category Next button correctly
todo 3 items:

1. only activate Next on sub-category page when user drills down all the way. some sub-categories have tertiary categories

2. format dropdown on sub-category so that the dropdown takes the full width

3. in market creation form if template has tertiary category hide the category picker.

### PR DESCRIPTION
**Pull request by bthaile**
added in tertiary dropdown for sub-categories that have tertiary categories
closes https://github.com/augurproject/augur/issues/4361
closes https://github.com/augurproject/augur/issues/4360
closes https://github.com/AugurProject/augur/issues/4377

user nav to sub-category template page, 
image

select category with tertiary
image

hide tertiary if category doesn't have tertiary
image

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This pull request has been automatically deployed to [FeaturePeek](https://featurepeek.com). 🍉

 This link will always point to this PR's latest changes: https://peek.run/o9ph7pq

**Review by phoebemirman — CHANGES_REQUESTED** [review]
1. can you make it so the dropdown is disabled when a category is not selected aka when you first land on the sub category picker



2. there is a bug where if you selected a sub category without any tertiaries then when you select another sub category with tertiaries then the dropdown stays disabled

**Review by phoebemirman — CHANGES_REQUESTED** [review]
Screen Shot 2019-10-22 at 6 07 49 PM


should we be disabling tertiary dropdown here too?

**Comment by bthaile** [comment]
I talked to Chwy about that, it doesn't effect the market only the location in the category tree. so it is fine to allow user to add to more sub categories than template categories

**Comment by phoebemirman** [comment]
No i mean letting them change the tertiary they set in the previous step. Wouldnt that make it so the market question dropdowns would change? Seems like another ui issue if we let them change it.

**Comment by bthaile** [comment]
yes, we'll need to disable the tertiary if newMarket already has tertiary in categories.

update <https://github.com/AugurProject/augur/issues/4377> to add in hiding category picker if categories are populated from template

**Review by bthaile — COMMENTED** [review]
lgtm

**Review by phoebemirman — APPROVED** [review]

**Pull request merged**
